"""Storage Protocol — mirrors the Rust `DynStorage` trait (Phase-1 subset)."""

from __future__ import annotations

from typing import Protocol

from oauth2_server.models import (
    AuditLogEntry,
    AuthorizationCode,
    Client,
    DenylistEntry,
    DeviceAuthorization,
    Token,
    User,
)
from oauth2_server.storage.paging import ListQuery


class Storage(Protocol):
    async def init(self) -> None: ...

    # Clients
    async def save_client(self, client: Client) -> None: ...
    async def get_client(self, client_id: str) -> Client | None: ...
    async def update_client(self, client: Client) -> None: ...
    async def delete_client(self, client_id: str) -> None: ...
    async def set_client_enabled(self, client_id: str, enabled: bool) -> None: ...
    async def set_client_secret(self, client_id: str, client_secret: str) -> None: ...
    async def list_all_clients(self) -> list[Client]: ...
    async def list_clients_page(self, q: ListQuery) -> tuple[list[Client], int]: ...

    # Users
    async def save_user(self, user: User) -> None: ...
    async def get_user_by_username(self, username: str) -> User | None: ...
    async def get_user_by_id(self, user_id: str) -> User | None: ...
    async def update_user(self, user: User) -> None: ...
    async def delete_user(self, user_id: str) -> None: ...
    async def set_user_enabled(self, user_id: str, enabled: bool) -> None: ...
    async def set_user_role(self, user_id: str, role: str) -> None: ...
    async def set_user_password_hash(self, user_id: str, password_hash: str) -> None: ...
    async def list_all_users(self) -> list[User]: ...
    async def list_users_page(self, q: ListQuery) -> tuple[list[User], int]: ...

    # Tokens
    async def save_token(self, token: Token) -> None: ...
    async def get_token_by_access_token(self, access_token: str) -> Token | None: ...
    async def get_token_by_refresh_token(self, refresh_token: str) -> Token | None: ...
    async def get_token_by_id(self, token_id: str) -> Token | None: ...
    async def revoke_token(self, token: str) -> None: ...
    async def revoke_token_family(self, family: str) -> int: ...
    async def revoke_tokens_by_user_id(self, user_id: str) -> int: ...
    async def revoke_tokens_by_client_id(self, client_id: str) -> int: ...
    async def list_all_tokens(self) -> list[Token]: ...
    async def list_tokens_page(self, q: ListQuery) -> tuple[list[Token], int]: ...

    # Authorization codes
    async def save_authorization_code(self, code: AuthorizationCode) -> None: ...
    async def get_authorization_code(self, code: str) -> AuthorizationCode | None: ...
    async def mark_authorization_code_used(self, code: str) -> int: ...

    # Device authorizations (RFC 8628)
    async def save_device_authorization(self, d: DeviceAuthorization) -> None: ...
    async def get_device_authorization_by_device_code(
        self, device_code: str
    ) -> DeviceAuthorization | None: ...
    async def get_device_authorization_by_user_code(
        self, user_code: str
    ) -> DeviceAuthorization | None: ...
    async def approve_device_authorization(self, user_code: str, user_id: str) -> None: ...
    async def deny_device_authorization(self, user_code: str) -> None: ...
    async def mark_device_authorization_used(self, device_code: str) -> int: ...
    async def expire_device_authorization(self, device_code: str) -> None: ...
    async def list_all_device_authorizations(self) -> list[DeviceAuthorization]: ...
    async def list_device_authorizations_page(
        self, q: ListQuery
    ) -> tuple[list[DeviceAuthorization], int]: ...

    # Denylist
    async def add_denylist_entry(self, entry: DenylistEntry) -> None: ...
    async def remove_denylist_entry(self, entry_id: str) -> None: ...
    async def list_denylist(self, q: ListQuery) -> tuple[list[DenylistEntry], int]: ...
    async def find_denylist_entry(self, kind: str, value: str) -> DenylistEntry | None: ...

    # Audit log
    async def write_audit_log(self, entry: AuditLogEntry) -> None: ...
    async def list_audit_log(self, q: ListQuery) -> tuple[list[AuditLogEntry], int]: ...
