"""Storage Protocol — mirrors the Rust `DynStorage` trait (Phase-1 subset)."""
from __future__ import annotations

from typing import Protocol

from oauth2_server.models import (
    AuthorizationCode,
    Client,
    DeviceAuthorization,
    Token,
    User,
)


class Storage(Protocol):
    async def init(self) -> None: ...

    # Clients
    async def save_client(self, client: Client) -> None: ...
    async def get_client(self, client_id: str) -> Client | None: ...
    async def update_client(self, client: Client) -> None: ...
    async def delete_client(self, client_id: str) -> None: ...

    # Users
    async def save_user(self, user: User) -> None: ...
    async def get_user_by_username(self, username: str) -> User | None: ...
    async def get_user_by_id(self, user_id: str) -> User | None: ...

    # Tokens
    async def save_token(self, token: Token) -> None: ...
    async def get_token_by_access_token(self, access_token: str) -> Token | None: ...
    async def get_token_by_refresh_token(self, refresh_token: str) -> Token | None: ...
    async def revoke_token(self, token: str) -> None: ...
    async def set_token_family(self, access_token: str, family: str) -> None: ...
    async def revoke_token_family(self, family: str) -> int: ...

    # Authorization codes
    async def save_authorization_code(self, code: AuthorizationCode) -> None: ...
    async def get_authorization_code(self, code: str) -> AuthorizationCode | None: ...
    async def mark_authorization_code_used(self, code: str) -> None: ...

    # Device authorizations (RFC 8628)
    async def save_device_authorization(self, d: DeviceAuthorization) -> None: ...
    async def get_device_authorization_by_device_code(
        self, device_code: str
    ) -> DeviceAuthorization | None: ...
    async def get_device_authorization_by_user_code(
        self, user_code: str
    ) -> DeviceAuthorization | None: ...
    async def approve_device_authorization(self, user_code: str, user_id: str) -> None: ...
    async def deny_device_authorization(self, user_code: str) -> None: ...
    async def mark_device_authorization_used(self, device_code: str) -> None: ...
    async def expire_device_authorization(self, device_code: str) -> None: ...
